# Create 1000 Wordlist in the list

word_list = [
    "Serendipity",
    "Mellifluous",
    "Resplendent",
    "Ephemeral",
    "Quixotic",
    "Obfuscate",
    "Zephyr",
    "Ebullient",
    "Perseverance",
    "Petrichor",
    "Vicarious",
    "Ineffable",
    "Mellifluous",
    "Penultimate",
    "Labyrinth",
    "Epiphany",
    "Paradox",
    "Ethereal",
    "Solitude",
    "Sonder",
    "Eloquence",
    "Serenity",
    "Magnanimous",
    "Nostalgia",
    "Effervescent",
]
